version: '3.8'

services:
  backend:
    build:
      context: ./backend/backend-todo
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://mongodb:27017/todo-app
      - JWT_SECRET=secret
    depends_on:
      - mongodb
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend/todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - todo-network

  mongodb:
    image: mongo:latest
    container_name: todo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongodb_data: 